@startuml
left to right direction

actor Recepcionista

rectangle "Sistema DentalFlow - Módulo Agenda" {
    usecase "Agendar Cita Médica" as UC_Agendar
    usecase "Validar Disponibilidad de Odontólogo" as UC_ValDisp
    usecase "Notificar Conflicto de Horario" as UC_Conflicto
    usecase "Cambiar Estado de Cita" as UC_Estado
}

Recepcionista --> UC_Agendar
Recepcionista --> UC_Estado
UC_Agendar ..> UC_ValDisp : <<include>>
UC_ValDisp <.. UC_Conflicto : <<extend>>
@enduml